# Generated by Django 5.0.1 on 2025-12-24 02:06

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('articles', '0002_article_viewer_models'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OpportunityBatch',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier (UUID)', primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False, help_text='Timestamp when record was created', verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when record was last updated', verbose_name='Updated At')),
                ('name', models.CharField(blank=True, max_length=200, verbose_name='Batch Name')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], db_index=True, default='pending', max_length=20)),
                ('config', models.JSONField(blank=True, default=dict, help_text='Settings used for this batch', verbose_name='Configuration')),
                ('topic_filter', models.CharField(blank=True, max_length=100)),
                ('region_filter', models.CharField(blank=True, max_length=100)),
                ('min_score', models.IntegerField(default=0)),
                ('max_article_age_days', models.IntegerField(default=7)),
                ('articles_analyzed', models.IntegerField(default=0)),
                ('opportunities_found', models.IntegerField(default=0)),
                ('task_id', models.CharField(blank=True, max_length=100)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True)),
                ('llm_tokens_used', models.IntegerField(default=0)),
                ('llm_cost', models.DecimalField(decimal_places=6, default=0, max_digits=10)),
            ],
            options={
                'verbose_name': 'Opportunity Batch',
                'verbose_name_plural': 'Opportunity Batches',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SynthesisTemplate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier (UUID)', primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False, help_text='Timestamp when record was created', verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when record was last updated', verbose_name='Updated At')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('content_type', models.CharField(choices=[('blog_post', 'Blog Post'), ('newsletter', 'Newsletter'), ('social_thread', 'Social Media Thread'), ('executive_summary', 'Executive Summary'), ('research_brief', 'Research Brief'), ('press_release', 'Press Release'), ('analysis', 'Analysis Piece'), ('commentary', 'Commentary')], default='blog_post', max_length=50)),
                ('prompt_template', models.TextField(help_text='The prompt template with {placeholders}', verbose_name='Prompt Template')),
                ('system_prompt', models.TextField(blank=True, verbose_name='System Prompt')),
                ('default_voice', models.CharField(choices=[('analytical', 'Analytical'), ('conversational', 'Conversational'), ('formal', 'Formal'), ('urgent', 'Urgent/Breaking'), ('educational', 'Educational'), ('persuasive', 'Persuasive')], default='analytical', max_length=50)),
                ('target_word_count', models.IntegerField(default=500)),
                ('max_tokens', models.IntegerField(default=1500)),
                ('is_active', models.BooleanField(default=True)),
                ('usage_count', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ContentOpportunity',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier (UUID)', primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False, help_text='Timestamp when record was created', verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when record was last updated', verbose_name='Updated At')),
                ('headline', models.CharField(help_text='Proposed headline for this content', max_length=300, verbose_name='Headline')),
                ('angle', models.TextField(help_text='The unique angle or hook for this content', verbose_name='Angle/Hook')),
                ('summary', models.TextField(blank=True, help_text='Brief summary of the opportunity', verbose_name='Summary')),
                ('opportunity_type', models.CharField(choices=[('trending', 'Trending Topic'), ('gap', 'Coverage Gap'), ('follow_up', 'Follow-up Story'), ('deep_dive', 'Deep Dive Analysis'), ('comparison', 'Comparative Analysis'), ('explainer', 'Explainer/Educational'), ('roundup', 'Roundup/Summary'), ('breaking', 'Breaking News'), ('evergreen', 'Evergreen Content')], db_index=True, default='trending', max_length=50, verbose_name='Type')),
                ('primary_topic', models.CharField(blank=True, db_index=True, max_length=100, verbose_name='Primary Topic')),
                ('secondary_topics', models.JSONField(blank=True, default=list, verbose_name='Secondary Topics')),
                ('primary_region', models.CharField(blank=True, db_index=True, max_length=100, verbose_name='Primary Region')),
                ('secondary_regions', models.JSONField(blank=True, default=list, verbose_name='Secondary Regions')),
                ('confidence_score', models.FloatField(default=0.5, help_text='How confident we are in this opportunity (0-1)', validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)], verbose_name='Confidence Score')),
                ('relevance_score', models.FloatField(default=0.5, help_text='How relevant this is to target audience (0-1)', validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)], verbose_name='Relevance Score')),
                ('timeliness_score', models.FloatField(default=0.5, help_text='How time-sensitive this opportunity is (0-1)', validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)], verbose_name='Timeliness Score')),
                ('composite_score', models.FloatField(db_index=True, default=0.0, help_text='Weighted combination of all scores', verbose_name='Composite Score')),
                ('priority', models.IntegerField(choices=[(1, 'Critical'), (2, 'High'), (3, 'Medium'), (4, 'Low'), (5, 'Optional')], db_index=True, default=3, verbose_name='Priority')),
                ('status', models.CharField(choices=[('detected', 'Detected'), ('reviewed', 'Reviewed'), ('approved', 'Approved'), ('in_progress', 'In Progress'), ('drafted', 'Drafted'), ('published', 'Published'), ('rejected', 'Rejected'), ('expired', 'Expired')], db_index=True, default='detected', max_length=20, verbose_name='Status')),
                ('source_article_count', models.IntegerField(default=0, verbose_name='Source Article Count')),
                ('detection_method', models.CharField(default='llm', help_text='How this opportunity was detected (llm, heuristic, manual)', max_length=50, verbose_name='Detection Method')),
                ('detection_reasoning', models.TextField(blank=True, help_text='Why this was identified as an opportunity', verbose_name='Detection Reasoning')),
                ('expires_at', models.DateTimeField(blank=True, db_index=True, help_text='When this opportunity becomes stale', null=True, verbose_name='Expires At')),
                ('reviewed_at', models.DateTimeField(blank=True, null=True, verbose_name='Reviewed At')),
                ('llm_tokens_used', models.IntegerField(default=0, verbose_name='LLM Tokens Used')),
                ('llm_cost', models.DecimalField(decimal_places=6, default=0, max_digits=10, verbose_name='LLM Cost')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_opportunities', to=settings.AUTH_USER_MODEL, verbose_name='Reviewed By')),
                ('source_articles', models.ManyToManyField(blank=True, help_text='Articles that contributed to this opportunity', related_name='opportunities', to='articles.article', verbose_name='Source Articles')),
            ],
            options={
                'verbose_name': 'Content Opportunity',
                'verbose_name_plural': 'Content Opportunities',
                'ordering': ['-composite_score', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ContentDraft',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier (UUID)', primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False, help_text='Timestamp when record was created', verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when record was last updated', verbose_name='Updated At')),
                ('title', models.CharField(max_length=300, verbose_name='Title')),
                ('subtitle', models.CharField(blank=True, max_length=500, verbose_name='Subtitle')),
                ('content', models.TextField(help_text='The generated content in Markdown format', verbose_name='Content')),
                ('content_html', models.TextField(blank=True, help_text='Rendered HTML version', verbose_name='Content HTML')),
                ('excerpt', models.TextField(blank=True, help_text='Short excerpt for previews', max_length=500, verbose_name='Excerpt')),
                ('content_type', models.CharField(choices=[('blog_post', 'Blog Post'), ('newsletter', 'Newsletter'), ('social_thread', 'Social Media Thread'), ('executive_summary', 'Executive Summary'), ('research_brief', 'Research Brief'), ('press_release', 'Press Release'), ('analysis', 'Analysis Piece'), ('commentary', 'Commentary')], db_index=True, default='blog_post', max_length=50, verbose_name='Content Type')),
                ('voice', models.CharField(choices=[('analytical', 'Analytical'), ('conversational', 'Conversational'), ('formal', 'Formal'), ('urgent', 'Urgent/Breaking'), ('educational', 'Educational'), ('persuasive', 'Persuasive')], default='analytical', max_length=50, verbose_name='Voice/Tone')),
                ('primary_topic', models.CharField(blank=True, db_index=True, max_length=100)),
                ('topics', models.JSONField(blank=True, default=list)),
                ('primary_region', models.CharField(blank=True, db_index=True, max_length=100)),
                ('regions', models.JSONField(blank=True, default=list)),
                ('tags', models.JSONField(blank=True, default=list)),
                ('status', models.CharField(choices=[('generating', 'Generating'), ('draft', 'Draft'), ('reviewing', 'Under Review'), ('approved', 'Approved'), ('published', 'Published'), ('rejected', 'Rejected'), ('archived', 'Archived')], db_index=True, default='generating', max_length=20)),
                ('source_article_count', models.IntegerField(default=0)),
                ('word_count', models.IntegerField(default=0)),
                ('reading_time_minutes', models.IntegerField(default=0)),
                ('quality_score', models.FloatField(default=0.0, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)], verbose_name='Quality Score')),
                ('originality_score', models.FloatField(default=0.0, help_text='How original vs derivative the content is', validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)], verbose_name='Originality Score')),
                ('version', models.IntegerField(default=1)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('llm_model', models.CharField(blank=True, max_length=100)),
                ('llm_tokens_used', models.IntegerField(default=0)),
                ('llm_cost', models.DecimalField(decimal_places=6, default=0, max_digits=10)),
                ('generation_time_seconds', models.FloatField(default=0)),
                ('task_id', models.CharField(blank=True, max_length=100)),
                ('error_message', models.TextField(blank=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_drafts', to=settings.AUTH_USER_MODEL)),
                ('parent_draft', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='revisions', to='content.contentdraft')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_drafts', to=settings.AUTH_USER_MODEL)),
                ('source_articles', models.ManyToManyField(blank=True, related_name='drafts', to='articles.article', verbose_name='Source Articles')),
                ('opportunity', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='drafts', to='content.contentopportunity', verbose_name='Source Opportunity')),
            ],
            options={
                'verbose_name': 'Content Draft',
                'verbose_name_plural': 'Content Drafts',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DraftFeedback',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier (UUID)', primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False, help_text='Timestamp when record was created', verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when record was last updated', verbose_name='Updated At')),
                ('feedback_type', models.CharField(choices=[('edit', 'Edit Request'), ('approve', 'Approval'), ('reject', 'Rejection'), ('comment', 'Comment'), ('regenerate', 'Regeneration Request')], default='comment', max_length=20)),
                ('content', models.TextField(verbose_name='Feedback Content')),
                ('section', models.CharField(blank=True, help_text='Which section this feedback applies to', max_length=100)),
                ('line_start', models.IntegerField(blank=True, null=True)),
                ('line_end', models.IntegerField(blank=True, null=True)),
                ('is_resolved', models.BooleanField(default=False)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('resolution_note', models.TextField(blank=True)),
                ('draft', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedback', to='content.contentdraft')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='contentopportunity',
            index=models.Index(fields=['status', 'priority'], name='content_con_status_44260b_idx'),
        ),
        migrations.AddIndex(
            model_name='contentopportunity',
            index=models.Index(fields=['opportunity_type', 'status'], name='content_con_opportu_d95b30_idx'),
        ),
        migrations.AddIndex(
            model_name='contentopportunity',
            index=models.Index(fields=['primary_topic', 'primary_region'], name='content_con_primary_663b44_idx'),
        ),
        migrations.AddIndex(
            model_name='contentopportunity',
            index=models.Index(fields=['-composite_score', '-created_at'], name='content_con_composi_953092_idx'),
        ),
        migrations.AddIndex(
            model_name='contentdraft',
            index=models.Index(fields=['status', 'content_type'], name='content_con_status_9dcb8b_idx'),
        ),
        migrations.AddIndex(
            model_name='contentdraft',
            index=models.Index(fields=['primary_topic', 'primary_region'], name='content_con_primary_be9789_idx'),
        ),
    ]
