# Generated by Django 6.0 on 2025-12-24 18:48

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0004_add_query_indexes'),
        ('content', '0001_content_opportunities_synthesis'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='contentopportunity',
            index=models.Index(fields=['expires_at', 'status'], name='content_con_expires_4aeaec_idx'),
        ),
    ]
