# Generated by Django 5.0.1 on 2025-12-23 23:07

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sources', '0005_crawljob_runs_extension'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SeedBatch',
            fields=[
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False, help_text='Timestamp when record was created', verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when record was last updated', verbose_name='Updated At')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, help_text='Optional name for this batch', max_length=200)),
                ('import_source', models.CharField(choices=[('csv', 'CSV Import'), ('json', 'JSON Import'), ('text', 'Text Import'), ('api', 'API')], default='text', max_length=50)),
                ('total_count', models.IntegerField(default=0)),
                ('success_count', models.IntegerField(default=0)),
                ('duplicate_count', models.IntegerField(default=0)),
                ('error_count', models.IntegerField(default=0)),
                ('errors', models.JSONField(blank=True, default=list, help_text='List of import errors')),
                ('imported_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='seed_batches', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Seed Batch',
                'verbose_name_plural': 'Seed Batches',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Seed',
            fields=[
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False, help_text='Timestamp when record was created', verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when record was last updated', verbose_name='Updated At')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('url', models.URLField(help_text='The seed URL to validate', max_length=2000)),
                ('domain', models.CharField(blank=True, help_text='Auto-extracted domain from URL', max_length=255)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('validating', 'Validating'), ('valid', 'Valid'), ('invalid', 'Invalid'), ('promoted', 'Promoted'), ('rejected', 'Rejected')], db_index=True, default='pending', max_length=20)),
                ('is_reachable', models.BooleanField(help_text='URL responds with 2xx status', null=True)),
                ('is_crawlable', models.BooleanField(help_text='robots.txt allows crawling', null=True)),
                ('has_articles', models.BooleanField(help_text='Page contains article links', null=True)),
                ('article_count_estimate', models.IntegerField(help_text='Estimated number of articles found', null=True)),
                ('validation_errors', models.JSONField(blank=True, default=list, help_text='List of validation error messages')),
                ('validated_at', models.DateTimeField(blank=True, help_text='When validation was last run', null=True)),
                ('notes', models.TextField(blank=True, help_text='Optional notes about this seed')),
                ('tags', models.JSONField(blank=True, default=list, help_text='Tags for categorization')),
                ('import_source', models.CharField(blank=True, choices=[('manual', 'Manual Entry'), ('csv', 'CSV Import'), ('json', 'JSON Import'), ('discovery', 'Auto-Discovery'), ('api', 'API')], default='manual', help_text='How this seed was added', max_length=50)),
                ('import_batch_id', models.UUIDField(blank=True, help_text='Batch ID if imported in bulk', null=True)),
                ('promoted_at', models.DateTimeField(blank=True, help_text='When this seed was promoted', null=True)),
                ('added_by', models.ForeignKey(blank=True, help_text='User who added this seed', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='added_seeds', to=settings.AUTH_USER_MODEL)),
                ('promoted_by', models.ForeignKey(blank=True, help_text='User who promoted this seed', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='promoted_seeds', to=settings.AUTH_USER_MODEL)),
                ('promoted_to', models.ForeignKey(blank=True, help_text='Source created from this seed', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='from_seeds', to='sources.source')),
            ],
            options={
                'verbose_name': 'Seed',
                'verbose_name_plural': 'Seeds',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status'], name='seeds_seed_status_70b5eb_idx'), models.Index(fields=['domain'], name='seeds_seed_domain_5c8ef2_idx'), models.Index(fields=['import_batch_id'], name='seeds_seed_import__40a8fd_idx')],
            },
        ),
    ]
