# Generated by Django 5.0.1 on 2025-12-24 00:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seeds', '0001_initial'),
        ('sources', '0005_crawljob_runs_extension'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='seed',
            name='confidence',
            field=models.IntegerField(default=50, help_text='Confidence score 0-100 for seed quality'),
        ),
        migrations.AddField(
            model_name='seed',
            name='country',
            field=models.CharField(blank=True, db_index=True, help_text='ISO 3166-1 alpha-2 country code', max_length=2),
        ),
        migrations.AddField(
            model_name='seed',
            name='discovered_from_run',
            field=models.ForeignKey(blank=True, help_text='Crawl run that discovered this seed', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='discovered_seeds', to='sources.crawljob'),
        ),
        migrations.AddField(
            model_name='seed',
            name='discovered_from_source',
            field=models.ForeignKey(blank=True, help_text='Source that discovered this seed', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='discovered_seeds', to='sources.source'),
        ),
        migrations.AddField(
            model_name='seed',
            name='normalized_url',
            field=models.CharField(blank=True, db_index=True, help_text='Normalized URL for deduplication', max_length=2000),
        ),
        migrations.AddField(
            model_name='seed',
            name='regions',
            field=models.JSONField(blank=True, default=list, help_text='List of region codes or names'),
        ),
        migrations.AddField(
            model_name='seed',
            name='seed_type',
            field=models.CharField(choices=[('unknown', 'Unknown'), ('news', 'News Site'), ('blog', 'Blog'), ('magazine', 'Magazine'), ('aggregator', 'Aggregator'), ('press_release', 'Press Release'), ('government', 'Government'), ('academic', 'Academic'), ('social', 'Social Media'), ('forum', 'Forum'), ('rss', 'RSS Feed'), ('sitemap', 'Sitemap')], db_index=True, default='unknown', help_text='Type/category of seed', max_length=20),
        ),
        migrations.AddField(
            model_name='seed',
            name='topics',
            field=models.JSONField(blank=True, default=list, help_text='List of topic tags'),
        ),
        migrations.AddIndex(
            model_name='seed',
            index=models.Index(fields=['seed_type'], name='seeds_seed_seed_ty_8eefbd_idx'),
        ),
        migrations.AddIndex(
            model_name='seed',
            index=models.Index(fields=['country'], name='seeds_seed_country_bc4292_idx'),
        ),
        migrations.AddIndex(
            model_name='seed',
            index=models.Index(fields=['confidence'], name='seeds_seed_confide_26ed7d_idx'),
        ),
        migrations.AddConstraint(
            model_name='seed',
            constraint=models.UniqueConstraint(condition=models.Q(('normalized_url__gt', '')), fields=('normalized_url',), name='unique_normalized_url'),
        ),
    ]
