# Generated by Django 6.0 on 2025-12-24 18:48

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seeds', '0002_add_seed_classification_fields'),
        ('sources', '0007_add_error_code_taxonomy'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='seed',
            index=models.Index(fields=['-created_at'], name='seeds_seed_created_eb9388_idx'),
        ),
        migrations.AddIndex(
            model_name='seed',
            index=models.Index(fields=['validated_at'], name='seeds_seed_validat_ce9d2a_idx'),
        ),
    ]
