# Generated by Django 6.0 on 2025-12-25 00:08

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seeds', '0004_discovery_architecture'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='seed',
            name='seeds_review_score_idx',
        ),
        migrations.RenameIndex(
            model_name='discoveryrun',
            new_name='seeds_disco_status_75e490_idx',
            old_name='seeds_discovery_status_idx',
        ),
        migrations.RenameIndex(
            model_name='discoveryrun',
            new_name='seeds_disco_created_396842_idx',
            old_name='seeds_discovery_created_idx',
        ),
        migrations.RenameIndex(
            model_name='seedrawcapture',
            new_name='seeds_seedr_body_ha_efe82a_idx',
            old_name='seeds_capture_hash_idx',
        ),
        migrations.RenameIndex(
            model_name='seedrawcapture',
            new_name='seeds_seedr_discove_9861f1_idx',
            old_name='seeds_capture_run_idx',
        ),
        migrations.RenameIndex(
            model_name='seedrawcapture',
            new_name='seeds_seedr_fetch_t_0078af_idx',
            old_name='seeds_capture_time_idx',
        ),
        migrations.AddField(
            model_name='seedrawcapture',
            name='content_length',
            field=models.IntegerField(default=0, help_text='Content-Length from response header (may differ from body_size if truncated)'),
        ),
        migrations.AddField(
            model_name='seedrawcapture',
            name='request_headers',
            field=models.JSONField(blank=True, default=dict, help_text='HTTP request headers sent'),
        ),
        migrations.AddField(
            model_name='seedrawcapture',
            name='truncated',
            field=models.BooleanField(default=False, help_text='True if body was truncated to MAX_CAPTURE_SIZE'),
        ),
        migrations.AlterField(
            model_name='discoveryrun',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False, help_text='Timestamp when record was created', verbose_name='Created At'),
        ),
        migrations.AlterField(
            model_name='discoveryrun',
            name='started_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='discovery_runs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='discoveryrun',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, help_text='Timestamp when record was last updated', verbose_name='Updated At'),
        ),
        migrations.AlterField(
            model_name='seedrawcapture',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False, help_text='Timestamp when record was created', verbose_name='Created At'),
        ),
        migrations.AlterField(
            model_name='seedrawcapture',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, help_text='Timestamp when record was last updated', verbose_name='Updated At'),
        ),
        migrations.AddIndex(
            model_name='seedrawcapture',
            index=models.Index(fields=['url'], name='seeds_seedr_url_880407_idx'),
        ),
    ]
