# Generated by Django 5.0.1 on 2025-12-23 22:31

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OperatorProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier (UUID)', primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False, help_text='Timestamp when record was created', verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when record was last updated', verbose_name='Updated At')),
                ('role', models.CharField(choices=[('admin', 'Administrator'), ('operator', 'Operator'), ('viewer', 'Viewer')], db_index=True, default='operator', help_text='User role determining permissions', max_length=20, verbose_name='Role')),
                ('preferences', models.JSONField(blank=True, default=dict, help_text='UI and workflow preferences', verbose_name='Preferences')),
                ('timezone', models.CharField(default='UTC', help_text='User preferred timezone', max_length=50, verbose_name='Timezone')),
                ('last_active_at', models.DateTimeField(blank=True, help_text='When user was last active in the console', null=True, verbose_name='Last Active')),
                ('user', models.OneToOneField(help_text='The associated Django user account', on_delete=django.db.models.deletion.CASCADE, related_name='operator_profile', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Operator Profile',
                'verbose_name_plural': 'Operator Profiles',
                'db_table': 'operator_profiles',
            },
        ),
    ]
