# Generated by Django 5.0.1 on 2025-12-23 23:29

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_operator_profile'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LLMSettings',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier (UUID)', primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False, help_text='Timestamp when record was created', verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when record was last updated', verbose_name='Updated At')),
                ('default_model', models.CharField(choices=[('claude-sonnet-4-20250514', 'Claude Sonnet 4'), ('claude-3-5-sonnet-20241022', 'Claude 3.5 Sonnet'), ('claude-3-5-haiku-20241022', 'Claude 3.5 Haiku'), ('gpt-4o', 'GPT-4o'), ('gpt-4o-mini', 'GPT-4o Mini')], default='claude-sonnet-4-20250514', help_text='Default LLM model for API calls', max_length=100, verbose_name='Default Model')),
                ('fallback_model', models.CharField(choices=[('claude-sonnet-4-20250514', 'Claude Sonnet 4'), ('claude-3-5-sonnet-20241022', 'Claude 3.5 Sonnet'), ('claude-3-5-haiku-20241022', 'Claude 3.5 Haiku'), ('gpt-4o', 'GPT-4o'), ('gpt-4o-mini', 'GPT-4o Mini')], default='claude-3-5-haiku-20241022', help_text='Fallback model when primary fails or budget is low', max_length=100, verbose_name='Fallback Model')),
                ('temperature', models.FloatField(default=0.7, help_text='Sampling temperature (0.0-1.0)', verbose_name='Temperature')),
                ('max_tokens', models.IntegerField(default=4096, help_text='Maximum output tokens per request', verbose_name='Max Tokens')),
                ('daily_budget_usd', models.DecimalField(decimal_places=2, default=10.0, help_text='Maximum daily spend on LLM API calls', max_digits=8, verbose_name='Daily Budget (USD)')),
                ('monthly_budget_usd', models.DecimalField(decimal_places=2, default=300.0, help_text='Maximum monthly spend on LLM API calls', max_digits=10, verbose_name='Monthly Budget (USD)')),
                ('budget_alert_threshold', models.FloatField(default=0.8, help_text='Alert when this percentage of budget is used (0.0-1.0)', verbose_name='Budget Alert Threshold')),
                ('enforce_budget', models.BooleanField(default=True, help_text='Block requests when budget is exceeded', verbose_name='Enforce Budget')),
                ('caching_enabled', models.BooleanField(default=True, help_text='Cache LLM responses to reduce costs', verbose_name='Response Caching')),
                ('cache_ttl_hours', models.IntegerField(default=24, help_text='How long to cache responses', verbose_name='Cache TTL (hours)')),
                ('ai_detection_enabled', models.BooleanField(default=True, help_text='Run AI content detection on articles', verbose_name='AI Detection Enabled')),
                ('content_analysis_enabled', models.BooleanField(default=True, help_text='Run LLM content analysis on articles', verbose_name='Content Analysis Enabled')),
                ('requests_per_minute', models.IntegerField(default=60, help_text='Max API requests per minute', verbose_name='Requests Per Minute')),
                ('is_active', models.BooleanField(default=True, help_text='Whether these settings are currently in use', verbose_name='Active')),
                ('last_modified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='llm_settings_changes', to=settings.AUTH_USER_MODEL, verbose_name='Last Modified By')),
            ],
            options={
                'verbose_name': 'LLM Settings',
                'verbose_name_plural': 'LLM Settings',
                'db_table': 'llm_settings',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='LLMUsageLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier (UUID)', primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False, help_text='Timestamp when record was created', verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when record was last updated', verbose_name='Updated At')),
                ('model', models.CharField(db_index=True, max_length=100, verbose_name='Model')),
                ('prompt_name', models.CharField(blank=True, db_index=True, max_length=100, verbose_name='Prompt Name')),
                ('prompt_version', models.CharField(blank=True, max_length=20, verbose_name='Prompt Version')),
                ('input_tokens', models.IntegerField(default=0, verbose_name='Input Tokens')),
                ('output_tokens', models.IntegerField(default=0, verbose_name='Output Tokens')),
                ('total_tokens', models.IntegerField(default=0, verbose_name='Total Tokens')),
                ('cost_usd', models.DecimalField(decimal_places=6, default=0, max_digits=10, verbose_name='Cost (USD)')),
                ('latency_ms', models.IntegerField(default=0, verbose_name='Latency (ms)')),
                ('cached', models.BooleanField(default=False, verbose_name='Cached Response')),
                ('success', models.BooleanField(default=True, verbose_name='Success')),
                ('error_type', models.CharField(blank=True, max_length=100, verbose_name='Error Type')),
                ('error_message', models.TextField(blank=True, verbose_name='Error Message')),
                ('article_id', models.UUIDField(blank=True, db_index=True, null=True, verbose_name='Article ID')),
                ('metadata', models.JSONField(blank=True, default=dict, verbose_name='Metadata')),
                ('triggered_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='llm_usage_logs', to=settings.AUTH_USER_MODEL, verbose_name='Triggered By')),
            ],
            options={
                'verbose_name': 'LLM Usage Log',
                'verbose_name_plural': 'LLM Usage Logs',
                'db_table': 'llm_usage_logs',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['created_at', 'model'], name='llm_usage_l_created_d0be72_idx'), models.Index(fields=['created_at', 'prompt_name'], name='llm_usage_l_created_214c2f_idx')],
            },
        ),
    ]
