# Generated by Django 5.0.1 on 2025-12-21 04:35

import django.core.validators
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Source',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier (UUID)', primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False, help_text='Timestamp when record was created', verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when record was last updated', verbose_name='Updated At')),
                ('name', models.CharField(help_text='Display name of the source', max_length=255, verbose_name='Source Name')),
                ('domain', models.CharField(db_index=True, help_text='Domain name (e.g., example.com)', max_length=255, unique=True, verbose_name='Domain')),
                ('url', models.URLField(help_text='Base URL for the source', max_length=500, verbose_name='Base URL')),
                ('source_type', models.CharField(choices=[('news_site', 'News Website'), ('blog', 'Blog'), ('government', 'Government Site'), ('research', 'Research Institution'), ('industry', 'Industry Publication'), ('social', 'Social Media'), ('other', 'Other')], default='news_site', help_text='Type of source', max_length=50, verbose_name='Source Type')),
                ('primary_region', models.CharField(blank=True, help_text='Primary geographic focus (e.g., Southeast Asia)', max_length=100, verbose_name='Primary Region')),
                ('primary_topics', models.JSONField(blank=True, default=list, help_text='List of primary topics covered', verbose_name='Primary Topics')),
                ('languages', models.JSONField(blank=True, default=list, help_text='Languages used by this source', verbose_name='Languages')),
                ('crawl_frequency_hours', models.IntegerField(default=24, help_text='How often to crawl this source (in hours)', validators=[django.core.validators.MinValueValidator(1)], verbose_name='Crawl Frequency (hours)')),
                ('crawler_type', models.CharField(default='scrapy', help_text='Type of crawler to use (scrapy, playwright, selenium)', max_length=50, verbose_name='Crawler Type')),
                ('crawler_config', models.JSONField(blank=True, default=dict, help_text='JSON configuration for the crawler', verbose_name='Crawler Configuration')),
                ('reputation_score', models.IntegerField(default=20, help_text='Source reputation score (0-100, affects article scoring)', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Reputation Score')),
                ('quality_indicators', models.JSONField(blank=True, default=dict, help_text='Tracked quality metrics for this source', verbose_name='Quality Indicators')),
                ('status', models.CharField(choices=[('active', 'Active'), ('probation', 'Probation'), ('inactive', 'Inactive'), ('blocked', 'Blocked')], db_index=True, default='active', help_text='Current status of the source', max_length=20, verbose_name='Status')),
                ('discovery_method', models.CharField(choices=[('manual', 'Manual Entry'), ('link_following', 'Link Following'), ('search', 'Search Discovery'), ('recommendation', 'Recommendation')], default='manual', help_text='How this source was discovered', max_length=50, verbose_name='Discovery Method')),
                ('discovered_at', models.DateTimeField(auto_now_add=True, help_text='When this source was added to the system', verbose_name='Discovered At')),
                ('total_articles_collected', models.IntegerField(default=0, help_text='Total number of articles collected from this source', verbose_name='Total Articles Collected')),
                ('total_articles_used', models.IntegerField(default=0, help_text='Number of articles used in content generation', verbose_name='Total Articles Used')),
                ('last_crawled_at', models.DateTimeField(blank=True, help_text='Last time this source was successfully crawled', null=True, verbose_name='Last Crawled')),
                ('last_successful_crawl', models.DateTimeField(blank=True, help_text='Last time crawl completed without errors', null=True, verbose_name='Last Successful Crawl')),
                ('crawl_errors_count', models.IntegerField(default=0, help_text='Number of consecutive crawl errors', verbose_name='Crawl Errors Count')),
                ('last_error_message', models.TextField(blank=True, help_text='Last error encountered during crawling', verbose_name='Last Error Message')),
                ('requires_javascript', models.BooleanField(default=False, help_text='Whether this source requires JavaScript rendering', verbose_name='Requires JavaScript')),
                ('robots_txt_compliant', models.BooleanField(default=True, help_text='Whether to respect robots.txt for this source', verbose_name='Robots.txt Compliant')),
                ('custom_headers', models.JSONField(blank=True, default=dict, help_text='Custom HTTP headers for crawling', verbose_name='Custom Headers')),
                ('notes', models.TextField(blank=True, help_text='Internal notes about this source', verbose_name='Notes')),
            ],
            options={
                'verbose_name': 'Source',
                'verbose_name_plural': 'Sources',
                'db_table': 'sources',
                'ordering': ['-reputation_score', 'name'],
                'indexes': [models.Index(fields=['domain'], name='sources_domain_281ca6_idx'), models.Index(fields=['status'], name='sources_status_1ece9b_idx'), models.Index(fields=['reputation_score'], name='sources_reputat_208d32_idx'), models.Index(fields=['last_crawled_at'], name='sources_last_cr_89065a_idx'), models.Index(fields=['primary_region'], name='sources_primary_adb487_idx')],
            },
        ),
    ]
