# Generated by Django 5.0.1 on 2025-12-21 04:50

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sources', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CrawlJob',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier (UUID)', primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False, help_text='Timestamp when record was created', verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when record was last updated', verbose_name='Updated At')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed')], db_index=True, default='pending', help_text='Current status of the crawl job', max_length=20, verbose_name='Status')),
                ('started_at', models.DateTimeField(blank=True, help_text='When the crawl job started', null=True, verbose_name='Started At')),
                ('completed_at', models.DateTimeField(blank=True, help_text='When the crawl job completed', null=True, verbose_name='Completed At')),
                ('total_found', models.IntegerField(default=0, help_text='Total number of potential articles found', verbose_name='Total Found')),
                ('new_articles', models.IntegerField(default=0, help_text='Number of new articles collected', verbose_name='New Articles')),
                ('duplicates', models.IntegerField(default=0, help_text='Number of duplicate articles skipped', verbose_name='Duplicates')),
                ('errors', models.IntegerField(default=0, help_text='Number of errors encountered', verbose_name='Errors')),
                ('error_message', models.TextField(blank=True, help_text='Error message if crawl failed', verbose_name='Error Message')),
                ('task_id', models.CharField(blank=True, help_text='Celery task ID', max_length=255, verbose_name='Task ID')),
                ('source', models.ForeignKey(help_text='The source being crawled', on_delete=django.db.models.deletion.CASCADE, related_name='crawl_jobs', to='sources.source', verbose_name='Source')),
            ],
            options={
                'verbose_name': 'Crawl Job',
                'verbose_name_plural': 'Crawl Jobs',
                'db_table': 'crawl_jobs',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['source', '-created_at'], name='crawl_jobs_source__b0d6bb_idx'), models.Index(fields=['status'], name='crawl_jobs_status_d9a592_idx'), models.Index(fields=['task_id'], name='crawl_jobs_task_id_2f73d1_idx')],
            },
        ),
    ]
