# Generated by Django 5.0.1 on 2025-12-23 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sources', '0003_crawljob_pages_crawled'),
    ]

    operations = [
        migrations.AddField(
            model_name='source',
            name='pagination_state',
            field=models.JSONField(blank=True, default=dict, help_text='Tracks successful pagination strategy and settings', verbose_name='Pagination State'),
        ),
    ]
