# Generated by Django 5.0.1 on 2025-12-23 22:34

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sources', '0004_add_pagination_state'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CrawlJobSourceResult',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier (UUID)', primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False, help_text='Timestamp when record was created', verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when record was last updated', verbose_name='Updated At')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed'), ('skipped', 'Skipped')], db_index=True, default='pending', help_text='Status of this source crawl', max_length=20, verbose_name='Status')),
                ('started_at', models.DateTimeField(blank=True, null=True, verbose_name='Started At')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='Completed At')),
                ('articles_found', models.IntegerField(default=0, verbose_name='Articles Found')),
                ('articles_new', models.IntegerField(default=0, verbose_name='New Articles')),
                ('articles_duplicate', models.IntegerField(default=0, verbose_name='Duplicate Articles')),
                ('pages_crawled', models.IntegerField(default=0, verbose_name='Pages Crawled')),
                ('errors_count', models.IntegerField(default=0, verbose_name='Error Count')),
                ('error_message', models.TextField(blank=True, verbose_name='Error Message')),
            ],
            options={
                'verbose_name': 'Crawl Job Source Result',
                'verbose_name_plural': 'Crawl Job Source Results',
                'db_table': 'crawl_job_source_results',
                'ordering': ['source__name'],
            },
        ),
        migrations.AddField(
            model_name='crawljob',
            name='config_overrides',
            field=models.JSONField(blank=True, default=dict, help_text='Runtime configuration overrides (max_pages, timeout, etc.)', verbose_name='Config Overrides'),
        ),
        migrations.AddField(
            model_name='crawljob',
            name='is_multi_source',
            field=models.BooleanField(default=False, help_text='Whether this run includes multiple sources', verbose_name='Multi-Source Run'),
        ),
        migrations.AddField(
            model_name='crawljob',
            name='priority',
            field=models.IntegerField(choices=[(1, 'Lowest'), (3, 'Low'), (5, 'Normal'), (7, 'High'), (9, 'Highest')], db_index=True, default=5, help_text='Run priority (1=lowest, 9=highest)', verbose_name='Priority'),
        ),
        migrations.AddField(
            model_name='crawljob',
            name='triggered_by',
            field=models.CharField(choices=[('manual', 'Manual'), ('schedule', 'Scheduled'), ('api', 'API')], db_index=True, default='manual', help_text='How this run was triggered', max_length=20, verbose_name='Triggered By'),
        ),
        migrations.AddField(
            model_name='crawljob',
            name='triggered_by_user',
            field=models.ForeignKey(blank=True, help_text='User who triggered this run (for manual/api triggers)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='triggered_crawl_jobs', to=settings.AUTH_USER_MODEL, verbose_name='Triggered By User'),
        ),
        migrations.AlterField(
            model_name='crawljob',
            name='source',
            field=models.ForeignKey(blank=True, help_text='The source being crawled (null for multi-source runs)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='crawl_jobs', to='sources.source', verbose_name='Source'),
        ),
        migrations.AlterField(
            model_name='crawljob',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], db_index=True, default='pending', help_text='Current status of the crawl job', max_length=20, verbose_name='Status'),
        ),
        migrations.AddIndex(
            model_name='crawljob',
            index=models.Index(fields=['priority', '-created_at'], name='crawl_jobs_priorit_6f82a4_idx'),
        ),
        migrations.AddIndex(
            model_name='crawljob',
            index=models.Index(fields=['triggered_by', '-created_at'], name='crawl_jobs_trigger_62fd0c_idx'),
        ),
        migrations.AddField(
            model_name='crawljobsourceresult',
            name='crawl_job',
            field=models.ForeignKey(help_text='The parent crawl job', on_delete=django.db.models.deletion.CASCADE, related_name='source_results', to='sources.crawljob', verbose_name='Crawl Job'),
        ),
        migrations.AddField(
            model_name='crawljobsourceresult',
            name='source',
            field=models.ForeignKey(help_text='The source being crawled', on_delete=django.db.models.deletion.CASCADE, related_name='crawl_results', to='sources.source', verbose_name='Source'),
        ),
        migrations.AddIndex(
            model_name='crawljobsourceresult',
            index=models.Index(fields=['crawl_job', 'status'], name='crawl_job_s_crawl_j_84b77a_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='crawljobsourceresult',
            unique_together={('crawl_job', 'source')},
        ),
    ]
