# Generated by Django 6.0 on 2025-12-24 04:14

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sources', '0005_crawljob_runs_extension'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='crawljob',
            index=models.Index(fields=['-started_at'], name='crawl_jobs_started_dd9b30_idx'),
        ),
        migrations.AddIndex(
            model_name='crawljob',
            index=models.Index(fields=['-completed_at'], name='crawl_jobs_complet_e5023a_idx'),
        ),
    ]
