# Generated by Django 6.0 on 2025-12-24 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sources', '0006_crawljob_date_indexes'),
    ]

    operations = [
        migrations.AddField(
            model_name='crawljobsourceresult',
            name='error_code',
            field=models.CharField(blank=True, help_text='Normalized error code for taxonomy (e.g., NETWORK_ERROR, TIMEOUT, ROBOTS_BLOCKED)', max_length=50, verbose_name='Error Code'),
        ),
    ]
