# Generated by Django 6.0 on 2025-12-25 01:41

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sources', '0007_add_error_code_taxonomy'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='crawljob',
            index=models.Index(fields=['status', '-started_at'], name='crawl_jobs_status_b68ace_idx'),
        ),
        migrations.AddIndex(
            model_name='crawljob',
            index=models.Index(fields=['status', '-completed_at'], name='crawl_jobs_status_7f3612_idx'),
        ),
    ]
