# Generated by Django 6.0 on 2025-12-25 05:49

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sources', '0010_crawl_control_center'),
    ]

    operations = [
        migrations.AddField(
            model_name='crawljob',
            name='custom_user_agent',
            field=models.CharField(blank=True, help_text='Custom user agent if mode is fixed', max_length=500, verbose_name='Custom User Agent'),
        ),
        migrations.AddField(
            model_name='crawljob',
            name='request_timeout',
            field=models.IntegerField(default=30, help_text='Timeout for individual requests', validators=[django.core.validators.MinValueValidator(5), django.core.validators.MaxValueValidator(120)], verbose_name='Request Timeout (sec)'),
        ),
        migrations.AddField(
            model_name='crawljob',
            name='retry_attempts',
            field=models.IntegerField(default=3, help_text='Number of retry attempts on failure', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)], verbose_name='Retry Attempts'),
        ),
        migrations.AddField(
            model_name='crawljob',
            name='retry_backoff',
            field=models.CharField(choices=[('exponential', 'Exponential'), ('linear', 'Linear'), ('constant', 'Constant')], default='exponential', help_text='How to increase delays between retries', max_length=20, verbose_name='Retry Backoff Strategy'),
        ),
        migrations.AddField(
            model_name='crawljob',
            name='user_agent_mode',
            field=models.CharField(choices=[('rotate', 'Rotate'), ('fixed', 'Fixed'), ('googlebot', 'Googlebot')], default='rotate', help_text='How to handle user agent strings', max_length=20, verbose_name='User Agent Mode'),
        ),
    ]
