# Generated by Django 5.0.1 on 2025-12-21 04:35

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sources', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier (UUID)', primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False, help_text='Timestamp when record was created', verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when record was last updated', verbose_name='Updated At')),
                ('url', models.URLField(db_index=True, help_text='Original URL of the article', max_length=1000, unique=True, verbose_name='URL')),
                ('title', models.CharField(help_text='Article title', max_length=500, verbose_name='Title')),
                ('author', models.CharField(blank=True, help_text='Article author(s)', max_length=200, verbose_name='Author')),
                ('published_date', models.DateTimeField(blank=True, db_index=True, help_text='When the article was published', null=True, verbose_name='Published Date')),
                ('collected_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='When we collected this article', verbose_name='Collected At')),
                ('raw_html', models.TextField(blank=True, help_text='Original HTML content', verbose_name='Raw HTML')),
                ('extracted_text', models.TextField(blank=True, help_text='Clean extracted text content', verbose_name='Extracted Text')),
                ('original_language', models.CharField(blank=True, help_text='Detected language code (e.g., es, fr, ar)', max_length=10, verbose_name='Original Language')),
                ('translated_text', models.TextField(blank=True, help_text='English translation (if not originally English)', verbose_name='Translated Text')),
                ('word_count', models.IntegerField(default=0, help_text='Number of words in the article', verbose_name='Word Count')),
                ('has_data_statistics', models.BooleanField(default=False, help_text='Whether article contains data/statistics', verbose_name='Has Statistics')),
                ('has_citations', models.BooleanField(default=False, help_text='Whether article cites sources', verbose_name='Has Citations')),
                ('images_count', models.IntegerField(default=0, help_text='Number of images in article', verbose_name='Images Count')),
                ('primary_region', models.CharField(blank=True, choices=[('southeast_asia', 'Southeast Asia'), ('central_asia', 'Central Asia'), ('africa', 'Africa'), ('latin_america', 'Latin America'), ('mena', 'MENA'), ('other', 'Other Emerging Markets')], db_index=True, help_text='Primary geographic region discussed', max_length=50, verbose_name='Primary Region')),
                ('secondary_regions', models.JSONField(blank=True, default=list, help_text='Additional regions mentioned', verbose_name='Secondary Regions')),
                ('primary_topic', models.CharField(blank=True, db_index=True, help_text='Main topic of the article', max_length=100, verbose_name='Primary Topic')),
                ('topics', models.JSONField(blank=True, default=list, help_text='All topics covered in the article', verbose_name='Topics')),
                ('reputation_score', models.IntegerField(default=0, help_text='Source reputation component (0-40 points)', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Reputation Score')),
                ('recency_score', models.IntegerField(default=0, help_text='Article age component (0-15 points)', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Recency Score')),
                ('topic_alignment_score', models.IntegerField(default=0, help_text='Topic relevance component (0-20 points)', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Topic Alignment Score')),
                ('content_quality_score', models.IntegerField(default=0, help_text='Content quality component (0-15 points)', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Content Quality Score')),
                ('geographic_relevance_score', models.IntegerField(default=0, help_text='Geographic relevance component (0-10 points)', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Geographic Relevance Score')),
                ('ai_penalty', models.IntegerField(default=0, help_text='Penalty if AI-generated content detected (0-15 points)', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='AI Penalty')),
                ('total_score', models.IntegerField(db_index=True, default=0, help_text='Combined score from all components', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Total Score')),
                ('ai_content_detected', models.BooleanField(db_index=True, default=False, help_text='Whether AI-generated content was detected', verbose_name='AI Content Detected')),
                ('ai_confidence_score', models.FloatField(default=0.0, help_text='Confidence level of AI detection (0-1)', validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)], verbose_name='AI Confidence Score')),
                ('ai_detection_reasoning', models.TextField(blank=True, help_text='Explanation of why AI content was detected', verbose_name='AI Detection Reasoning')),
                ('processing_status', models.CharField(choices=[('collected', 'Collected'), ('extracting', 'Extracting Text'), ('extracted', 'Text Extracted'), ('translating', 'Translating'), ('translated', 'Translated'), ('scoring', 'Scoring'), ('scored', 'Scored'), ('completed', 'Processing Complete'), ('failed', 'Processing Failed')], db_index=True, default='collected', help_text='Current processing stage', max_length=20, verbose_name='Processing Status')),
                ('processing_error', models.TextField(blank=True, help_text='Error message if processing failed', verbose_name='Processing Error')),
                ('used_in_content', models.BooleanField(db_index=True, default=False, help_text='Whether this article was used in content generation', verbose_name='Used in Content')),
                ('usage_count', models.IntegerField(default=0, help_text='Number of times used in content generation', verbose_name='Usage Count')),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Additional metadata (extraction info, etc.)', verbose_name='Metadata')),
                ('source', models.ForeignKey(help_text='The source this article was collected from', on_delete=django.db.models.deletion.CASCADE, related_name='articles', to='sources.source', verbose_name='Source')),
            ],
            options={
                'verbose_name': 'Article',
                'verbose_name_plural': 'Articles',
                'db_table': 'articles',
                'ordering': ['-total_score', '-collected_at'],
                'indexes': [models.Index(fields=['url'], name='articles_url_426d50_idx'), models.Index(fields=['source', 'collected_at'], name='articles_source__d0e908_idx'), models.Index(fields=['processing_status'], name='articles_process_1df9b8_idx'), models.Index(fields=['total_score'], name='articles_total_s_c1b6db_idx'), models.Index(fields=['primary_region', 'primary_topic'], name='articles_primary_4096f8_idx'), models.Index(fields=['published_date'], name='articles_publish_ab562d_idx'), models.Index(fields=['ai_content_detected'], name='articles_ai_cont_4b25da_idx'), models.Index(fields=['used_in_content'], name='articles_used_in_6830ff_idx')],
            },
        ),
    ]
