# Generated by Django 5.0.1 on 2025-12-23 23:17

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArticleImage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier (UUID)', primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False, help_text='Timestamp when record was created', verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when record was last updated', verbose_name='Updated At')),
                ('url', models.URLField(max_length=2000, verbose_name='Image URL')),
                ('alt_text', models.CharField(blank=True, max_length=500, verbose_name='Alt Text')),
                ('caption', models.TextField(blank=True, verbose_name='Caption')),
                ('position', models.IntegerField(default=0, help_text='Order of image in article', verbose_name='Position')),
                ('width', models.IntegerField(blank=True, null=True, verbose_name='Width')),
                ('height', models.IntegerField(blank=True, null=True, verbose_name='Height')),
                ('file_size', models.IntegerField(blank=True, null=True, verbose_name='File Size (bytes)')),
                ('content_type', models.CharField(blank=True, max_length=50, verbose_name='Content Type')),
                ('is_primary', models.BooleanField(default=False, verbose_name='Is Primary Image')),
                ('is_infographic', models.BooleanField(default=False, verbose_name='Is Infographic')),
                ('analysis', models.JSONField(blank=True, default=dict, help_text='LLM or CV analysis results', verbose_name='Image Analysis')),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='articles.article', verbose_name='Article')),
            ],
            options={
                'verbose_name': 'Article Image',
                'verbose_name_plural': 'Article Images',
                'ordering': ['article', 'position'],
            },
        ),
        migrations.CreateModel(
            name='ArticleRawCapture',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier (UUID)', primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False, help_text='Timestamp when record was created', verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when record was last updated', verbose_name='Updated At')),
                ('http_status', models.IntegerField(blank=True, help_text='HTTP status code from fetch', null=True, verbose_name='HTTP Status')),
                ('response_headers', models.JSONField(blank=True, default=dict, help_text='HTTP response headers', verbose_name='Response Headers')),
                ('request_headers', models.JSONField(blank=True, default=dict, help_text='HTTP request headers used', verbose_name='Request Headers')),
                ('fetch_method', models.CharField(blank=True, choices=[('requests', 'Requests'), ('playwright', 'Playwright'), ('scrapy', 'Scrapy'), ('hybrid', 'Hybrid')], max_length=50, verbose_name='Fetch Method')),
                ('fetch_duration_ms', models.IntegerField(blank=True, null=True, verbose_name='Fetch Duration (ms)')),
                ('fetched_at', models.DateTimeField(auto_now_add=True, verbose_name='Fetched At')),
                ('content_type', models.CharField(blank=True, max_length=100, verbose_name='Content Type')),
                ('content_length', models.IntegerField(blank=True, null=True, verbose_name='Content Length')),
                ('final_url', models.URLField(blank=True, help_text='URL after redirects', max_length=2000, verbose_name='Final URL')),
                ('article', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='raw_capture', to='articles.article', verbose_name='Article')),
            ],
            options={
                'verbose_name': 'Article Raw Capture',
                'verbose_name_plural': 'Article Raw Captures',
            },
        ),
        migrations.CreateModel(
            name='ArticleScoreBreakdown',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier (UUID)', primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False, help_text='Timestamp when record was created', verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when record was last updated', verbose_name='Updated At')),
                ('reputation_raw', models.FloatField(default=0.0, verbose_name='Reputation Raw Score')),
                ('reputation_weighted', models.FloatField(default=0.0, verbose_name='Reputation Weighted Score')),
                ('reputation_reasoning', models.TextField(blank=True, verbose_name='Reputation Reasoning')),
                ('recency_raw', models.FloatField(default=0.0, verbose_name='Recency Raw Score')),
                ('recency_weighted', models.FloatField(default=0.0, verbose_name='Recency Weighted Score')),
                ('recency_reasoning', models.TextField(blank=True, verbose_name='Recency Reasoning')),
                ('topic_raw', models.FloatField(default=0.0, verbose_name='Topic Alignment Raw Score')),
                ('topic_weighted', models.FloatField(default=0.0, verbose_name='Topic Alignment Weighted Score')),
                ('topic_reasoning', models.TextField(blank=True, verbose_name='Topic Reasoning')),
                ('quality_raw', models.FloatField(default=0.0, verbose_name='Content Quality Raw Score')),
                ('quality_weighted', models.FloatField(default=0.0, verbose_name='Content Quality Weighted Score')),
                ('quality_reasoning', models.TextField(blank=True, verbose_name='Quality Reasoning')),
                ('geographic_raw', models.FloatField(default=0.0, verbose_name='Geographic Relevance Raw Score')),
                ('geographic_weighted', models.FloatField(default=0.0, verbose_name='Geographic Relevance Weighted Score')),
                ('geographic_reasoning', models.TextField(blank=True, verbose_name='Geographic Reasoning')),
                ('ai_detection_raw', models.FloatField(default=0.0, verbose_name='AI Detection Raw Score')),
                ('ai_penalty_applied', models.FloatField(default=0.0, verbose_name='AI Penalty Applied')),
                ('ai_reasoning', models.TextField(blank=True, verbose_name='AI Detection Reasoning')),
                ('scoring_version', models.CharField(default='1.0', max_length=20, verbose_name='Scoring Version')),
                ('scored_at', models.DateTimeField(auto_now=True, verbose_name='Scored At')),
                ('article', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='score_breakdown', to='articles.article', verbose_name='Article')),
            ],
            options={
                'verbose_name': 'Article Score Breakdown',
                'verbose_name_plural': 'Article Score Breakdowns',
            },
        ),
        migrations.CreateModel(
            name='ArticleLLMArtifact',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier (UUID)', primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False, help_text='Timestamp when record was created', verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when record was last updated', verbose_name='Updated At')),
                ('artifact_type', models.CharField(choices=[('content_analysis', 'Content Analysis'), ('topic_extraction', 'Topic Extraction'), ('ai_detection', 'AI Detection'), ('relevance_scoring', 'Relevance Scoring'), ('translation', 'Translation'), ('summarization', 'Summarization'), ('entity_extraction', 'Entity Extraction'), ('other', 'Other')], db_index=True, max_length=50, verbose_name='Artifact Type')),
                ('prompt_name', models.CharField(blank=True, help_text='Name of the prompt template used', max_length=100, verbose_name='Prompt Name')),
                ('prompt_version', models.CharField(blank=True, max_length=20, verbose_name='Prompt Version')),
                ('prompt_text', models.TextField(blank=True, help_text='Complete prompt sent to LLM', verbose_name='Full Prompt')),
                ('response_text', models.TextField(blank=True, help_text='Raw response from LLM', verbose_name='Response Text')),
                ('response_parsed', models.JSONField(blank=True, default=dict, help_text='Structured parsed response', verbose_name='Parsed Response')),
                ('input_tokens', models.IntegerField(default=0, verbose_name='Input Tokens')),
                ('output_tokens', models.IntegerField(default=0, verbose_name='Output Tokens')),
                ('total_tokens', models.IntegerField(default=0, verbose_name='Total Tokens')),
                ('estimated_cost', models.DecimalField(decimal_places=6, default=0, max_digits=10, verbose_name='Estimated Cost (USD)')),
                ('model_name', models.CharField(blank=True, max_length=100, verbose_name='Model Name')),
                ('latency_ms', models.IntegerField(blank=True, null=True, verbose_name='Latency (ms)')),
                ('success', models.BooleanField(default=True, verbose_name='Success')),
                ('error_message', models.TextField(blank=True, verbose_name='Error Message')),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='llm_artifacts', to='articles.article', verbose_name='Article')),
            ],
            options={
                'verbose_name': 'Article LLM Artifact',
                'verbose_name_plural': 'Article LLM Artifacts',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['article', 'artifact_type'], name='articles_ar_article_eb1916_idx')],
            },
        ),
    ]
