# Generated by Django 6.0 on 2025-12-24 03:33

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0002_article_viewer_models'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ExportJob',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier (UUID)', primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False, help_text='Timestamp when record was created', verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when record was last updated', verbose_name='Updated At')),
                ('export_type', models.CharField(default='articles', help_text='Type of export (articles, sources, etc.)', max_length=50, verbose_name='Export Type')),
                ('status', models.CharField(choices=[('queued', 'Queued'), ('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed')], db_index=True, default='queued', max_length=20, verbose_name='Status')),
                ('format', models.CharField(choices=[('csv', 'CSV'), ('json', 'JSON'), ('markdown_zip', 'Markdown ZIP')], default='csv', max_length=20, verbose_name='Export Format')),
                ('params', models.JSONField(blank=True, default=dict, help_text='Query filters applied to this export', verbose_name='Filter Parameters')),
                ('file_path', models.CharField(blank=True, help_text='Path to generated file', max_length=500, verbose_name='File Path')),
                ('file_size', models.BigIntegerField(blank=True, null=True, verbose_name='File Size (bytes)')),
                ('row_count', models.IntegerField(blank=True, help_text='Number of records exported', null=True, verbose_name='Row Count')),
                ('error_message', models.TextField(blank=True, verbose_name='Error Message')),
                ('started_at', models.DateTimeField(blank=True, null=True, verbose_name='Started At')),
                ('finished_at', models.DateTimeField(blank=True, null=True, verbose_name='Finished At')),
                ('requested_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='export_jobs', to=settings.AUTH_USER_MODEL, verbose_name='Requested By')),
            ],
            options={
                'verbose_name': 'Export Job',
                'verbose_name_plural': 'Export Jobs',
                'db_table': 'export_jobs',
                'ordering': ['-created_at'],
            },
        ),
    ]
