# Generated by Django 6.0 on 2025-12-24 18:48

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0003_add_exportjob'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='exportjob',
            index=models.Index(fields=['requested_by', '-created_at'], name='export_jobs_request_a8d8b7_idx'),
        ),
    ]
